# Copyright (c) 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022 Python Software Foundation; All Rights Reserved
#
# SPDX-License-Identifier: PSF-2.0

name: Tests

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'LICENSE.*'
      - 'README.*'
      - '.github/ISSUE-TEMPLATE/**'
      - 'docs/**'
      - '.hgignore'
      - '.gitignore'

  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'LICENSE.*'
      - 'README.*'
      - '.github/ISSUE-TEMPLATE/**'
      - 'docs/**'
      - '.hgignore'
      - '.gitignore'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['2.7', '3.7', '3.8', '3.9', '3.10', 'pypy-2.7', 'pypy-3.7']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Test with unittest
      run: |
        python setup.py test -v
      env:
        PYTHONHASHSEED: 0
    - name: Test with coverage
      run: |
        pip install coverage
        coverage run --branch setup.py test
        coverage xml
      env:
        PYTHONHASHSEED: 0
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        flags: unittests
        files: coverage.xml
        fail_ci_if_error: true
